# Shadowrocket: 2026-08-06 22:31:05
[General]
direct-dns-server = 119.29.29.29
hijack-dns = 8.8.8.8:53
dns-server = 8.8.8.8
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
private-ip-answer = true
bypass-system = true
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
dns-direct-fallback-proxy = true

[Proxy Group]
Yes = fallback,🇹🇼TAIWAN 04,🇯🇵【亚洲】日本05三网优化丨VLESS 2X,🇹🇼TAIWAN 03,🇯🇵【亚洲】日本04三网优化丨VLESS 2X,🇹🇼【亚洲】台湾家宽01丨专线【3X】,policy-select-name=🇹🇼TAIWAN 04,interval=1200,timeout=1,url=https://www.google.com/generate_204

[Rule]
RULE-SET,https://raw.githubusercontent.com/kunkun0/shadowrocket-rules/refs/heads/main/rejectlist,REJECT
RULE-SET,https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list,REJECT-200
RULE-SET,https://raw.githubusercontent.com/kunkun0/shadowrocket-rules/refs/heads/main/directlist,DIRECT
RULE-SET,https://raw.githubusercontent.com/kunkun0/shadowrocket-rules/refs/heads/main/proxylist,YES
GEOIP,CN,DIRECT
FINAL,PROXY

[Host]
localhost = 127.0.0.1
